# Use the AWS Lambda Python runtime image
FROM public.ecr.aws/lambda/python:3.12

# Copy requirements.txt
COPY docker/backend/requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy the source code
COPY src/ ${LAMBDA_TASK_ROOT}/src/

# Set the CMD to your handler
CMD [ "src.app.handler" ]
